"""add_tranquis_tables

Revision ID: 509a7ca245fd
Revises: 5c1e7a9d3b42
Create Date: 2026-10-08 12:51:11.630879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509a7ca245fd'
down_revision: Union[str, None] = '5c1e7a9d3b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('source_lang', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_user_id'), 'translations', ['user_id'], unique=False)
    op.create_table('phrasebook',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('translation_id', sa.UUID(), nullable=True),
    sa.Column('source_lang', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrasebook_user_id'), 'phrasebook', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasebook_user_id'), table_name='phrasebook')
    op.drop_table('phrasebook')
    op.drop_index(op.f('ix_translations_user_id'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
