"""add_phrasebook_section_phonetic

Revision ID: 966a3aa0830c
Revises: 509a7ca245fd
Create Date: 2026-10-09 08:35:11.254424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966a3aa0830c'
down_revision: Union[str, None] = '509a7ca245fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrasebook', sa.Column('section', sa.String(), nullable=True))
    op.add_column('phrasebook', sa.Column('phonetic', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phrasebook', 'phonetic')
    op.drop_column('phrasebook', 'section')
    # ### end Alembic commands ###
